name: WSO2 Streaming Integrator Docs Publish

env:
  BRANCH_NAME: ${{ github.ref_name }}

on:
  push:
    branches:
      - main
      - 4.3.0
  workflow_dispatch:

jobs:
  release-si-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r en/requirements.txt

      - name: Build MkDocs Documentation
        run: |
          git config --global user.email "ballerina-bot@ballerina.org"
          git config --global user.name "ballerina-bot"
          cd en/
          if [ "$BRANCH_NAME" = "main" ]; then
            mike deploy 4.3.1 latest -t "4.3.1" --push
          else
            mike deploy 4.3.0 -t "<= 4.3.0" --push
          fi
